### ISSUE TITLE
Bad Gateway with docker image etherpad:1.8.9

### ISSUE THREAD

**Issue by mbauer92** [spruce/ep_small_list#9]
I case this is of interest:
Trying to use the plugin (installed via npm install ep_small_list) with the etherpad docker image (tested with version 1.8.9) results in a 502 http status response on any url.
This is fixed by returning the callback empty (return cb();) at the end of the registerRoute function (https://github.com/spruce/ep_small_list/blob/22b521740d2e1b59d3031227f413fed1290784bd/index.js#L52).

**Comment by spruce** [comment]
Sorry for the delay. Could you create a PR fixing that?

**Comment by milanbargiel** [comment]
Thanks, I faced the same issue.

**Comment by crummy** [comment]
I think I have the same problem. This works for me, after `git clone git@github.com:ether/etherpad-lite.git`:

```
version: '2.4'

services:
  etherpad:
    depends_on:
      - etherpad_db
    build:
      context: ./etherpad-lite
    container_name: etherpad
    restart: always
    ports:
      - "9001:9001"
    environment:
      LOGLEVEL: "debug"
```
Then `docker-compose up -d --build`.

This does not work for me:
```
version: '2.4'

services:
  etherpad:
    depends_on:
      - etherpad_db
    build:
      context: ./etherpad-lite
      args:
        ETHERPAD_PLUGINS: "ep_small_list"
    container_name: etherpad
    restart: always
    ports:
      - "9001:9001"
    environment:
      LOGLEVEL: "debug"
```

The container goes unhealthy after a while and never responds on 9001.
